services:
    behavior.publishable.extension:
        class: BehaviorBundle\Admin\Extension\PublishableAdminExtension
        tags:
            - { name: sonata.admin.extension }

    behavior.publishable.filter:
        class: BehaviorBundle\Filter\PublishableFilter
        arguments: [ @doctrine.orm.entity_manager ]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    behavior.sluggable.listener:
        class: BehaviorBundle\EventListener\SluggableListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: onPrePersist }

    behavior.sortable.extension:
        class: BehaviorBundle\Admin\Extension\SortableAdminExtension
        tags:
            - { name: sonata.admin.extension }

    behavior.sortable.listener:
        class: BehaviorBundle\EventListener\SortableListener
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: onPostPersist }
            - { name: doctrine.event_listener, event: preUpdate, method: onPreUpdate }

    behavior.timestampable.listener:
        class: BehaviorBundle\EventListener\TimestampableListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: onPrePersist }
            - { name: doctrine.event_listener, event: preUpdate, method: onPreUpdate }

    behavior.translatable.filter:
        class: BehaviorBundle\Filter\TranslatableFilter
        arguments: [ @doctrine.orm.entity_manager ]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    behavior.translatable.listener:
        class: BehaviorBundle\EventListener\TranslatableListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata , method: onLoadClassMetadata }

    behavior.translation.extension:
        class: BehaviorBundle\Admin\Extension\TranslationAdminExtension
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: sonata.admin.extension }

    behavior.traversable.listener:
        class: BehaviorBundle\EventListener\TraversableListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata , method: onLoadClassMetadata }

    behavior.traversable.extension:
        class: BehaviorBundle\Admin\Extension\TraversableAdminExtension
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: sonata.admin.extension }
