# Translations of prefixes for multilingual routes can be defined in
# src/AppBundle/Resources/translations/routes.<lang>.yml

api_rest:
    resource: "@ApiBundle/Resources/config/routes.yml"
    type: rest
    prefix: /api
    options: { i18n: false }

app:
    resource: "@AppBundle/Controller/"
    type: annotation

messaging:
    resource: "@MessagingBundle/Controller/"
    type: annotation
    prefix: /messaging

news:
    resource: "@NewsBundle/Controller/"
    type: annotation
    prefix: /news

pdf:
    resource: "@PdfBundle/Controller/"
    type: annotation
    prefix: /pdf

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /apidoc

search:
    resource: "@SearchBundle/Controller/"
    type: annotation
    prefix: /search

sitemap:
    resource: "@SitemapBundle/Controller/"
    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /oauth-connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /oauth-login

google_login:
    pattern: /oauth-login/check-google

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
    prefix: /admin

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /admin/resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /admin/profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /admin/register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /admin/profile

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

page:
    resource: "@PageBundle/Controller/"
    type: annotation
