security:
    acl:
        connection: default

    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_API_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_API_USER:    []
        ROLE_API_ADMIN:   [ROLE_API_USER]

    providers:
        fos_userbundle:
            id: user.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_wsse:
            pattern: ^/api/.*
            wsse: true
            stateless: true
            anonymous: false

        api_oauth:
            pattern: ^/api/.*
            fos_oauth: true
            stateless: true
            anonymous: false

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        oauth_authorize:
            pattern: ^/oauth/v2/auth
            form_login:
                 provider: fos_userbundle
                 check_path: /oauth/v2/auth/login_check
                 login_path: /oauth/v2/auth/login
            anonymous: true

        admin:
            pattern: .*
            form-login:
                provider: fos_userbundle
                login_path: /admin/login
                use_forward: false
                check_path: /admin/login_check
                failure_path: /admin/login
                default_target_path: /admin/dashboard
            oauth:
                resource_owners:
                    google: /oauth-login/check-google
                login_path: /admin/login
                use_forward: false
                failure_path: /admin/login
                default_target_path: /admin/dashboard
                oauth_user_provider:
                    service: user.user_provider
            logout:
                path: /admin/logout
                target: /
            anonymous: true

    access_control:
        - { path: ^/api/, role: ROLE_API_USER }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
