services:
    page.admin.page:
        class: PageBundle\Admin\PageAdmin
        arguments: [ null, PageBundle\Entity\Page, null]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Pages, label_catalogue: messages }

    page.route_provider:
        class: PageBundle\Service\RouteProvider
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            -  { name: route.provider }
