services:
    user.user_provider:
        class: UserBundle\Model\UserProvider
        arguments: [ @fos_user.user_manager, { google: googleId } ]
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]

    user.user.handler:
        class: UserBundle\Handler\UserHandler
        arguments: [ @doctrine.orm.entity_manager, UserBundle\Entity\User ]

    user.user_listener:
        class: UserBundle\EventListener\UserListener
        tags:
           - { name: doctrine.event_listener, event: postPersist }
