services:
    app.route_provider:
        class: AppBundle\Service\RouteProvider
        tags:
            -  { name: route.provider }

    app.create.object_mapper:
        class: Midgard\CreatePHP\Mapper\DoctrineOrmMapper
        arguments: [ cmf_create.map, @doctrine, null]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
